### ISSUE TITLE
iPhone X : QR code not working.

### ISSUE THREAD

**Issue by ManojMM026** [Furkankyl/twitter_qr_scanner#1]
For android it Lib works great. 
For iPhone X it doesn't work. Please see following log:

![IMG_2207](https://user-images.githubusercontent.com/2713390/74828520-3ffae200-5335-11ea-99c9-86f5681645a0.PNG)

`Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.anka.twitter_qr_scanner/qrview')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:168:41)
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:621:71)
#4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:571:5)
#5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:581:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#9      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#15     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#41     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#43     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
#44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#48     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#49     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#62     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#63     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#70     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#75     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#79     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#81     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#93     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#95     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#101    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#105    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#114    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#120    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#126    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#129    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#134    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#139    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5551:32)
#140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#145    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#146    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#149    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#151    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#153    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#155    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#158    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#159    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#162    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#163    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#164    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#165    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#166    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#167    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#168    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#169    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#175    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#176    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#180    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#181    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#182    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#183    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#184    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#186    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#187    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#188    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#189    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#190    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#191    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#192    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#193    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#194    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#198    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#201    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#203    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#205    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#207    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#208    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#209    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#210    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#211    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#212    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#213    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#214    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#217    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#219    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#222    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#223    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#224    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#225    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#227    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#228    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#229    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#230    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#232    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#233    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#235    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#236    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#237    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#238    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#239    Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#240    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5219:32)
#241    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
#242    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#243    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:605:16)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#245    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#246    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#247    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#248    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#249    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#250    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#251    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
#252    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
#253    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#254    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#255    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#256    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#257    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#258    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#260    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#261    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#262    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
#263    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#264    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#265    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#266    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
#267    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
#268    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#269    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#270    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#271    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#272    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#273    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#274    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#275    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#276    _rootRun (dart:async/zone.dart:1126:13)
#277    _CustomZone.run (dart:async/zone.dart:1023:19)
#278    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#279    _invoke (dart:ui/hooks.dart:259:10)
#280    _drawFrame (dart:ui/hooks.dart:217:3)`

**Comment by Furkankyl** [comment]
which version are you using?

**Comment by ManojMM026** [comment]
iOS: 13.1.2
pub: twitter_qr_scanner: ^1.0.4

```
return Scaffold(
      floatingActionButton: _isCameraPaused
          ? FloatingActionButton(
              mini: true,
              onPressed: () => onRetake(),
              child: Icon(getIconUsingPrefix(name: "fa.undoAlt")),
            )
          : null,
      body: Container(
        child: QRView(
          key: qrKey,
          overlay: QrScannerOverlayShape(
              borderRadius: 16,
              borderColor: AppColors.getIconColor(context),
              borderWidth: 5,

              ///complete border (make it less 50 or so you will see border cut to only corner
              borderLength: AppConstants.deviceWidth * 0.50 / 2,

              ///QR CODE SIZE
              cutOutSize: AppConstants.deviceWidth * 0.50),
          onQRViewCreated: _onQRViewCreate,
          data: "QR TEXT",
        ),
      ),
    );
```

**Comment by egaga** [comment]
In the `carousel_slider` dependency of this plugin, in line _289_ there is 
`if (widget.pageController.position.minScrollExtent == null ||`

When I add a debug point 
<img width="459" alt="Screenshot 2021-06-11 at 10 37 22" src="https://user-images.githubusercontent.com/138295/121649331-2557f980-caa1-11eb-9a97-832e8988acfa.png">

you can see that the `_minScrollExtent` is `null`.
So the `double get minScrollExtent => _minScrollExtent!;` will definitely fail.

This makes sense to me and seems to be related to this PR because my stack trace has also: 
`Unhandled Exception: PlatformException(unregistered_view_type, trying to create a view with an unregistered type, unregistered view type: 'com.anka.twitter_qr_scanner/qrview', null).`

But along with that I get also `Null check operator used on a null value`.

Of course, could be an unrelated error.

I hope this package will be have its dependencies updated and this package will be upgraded to work with null safety.

I have Flutter version 2.2.1 (channel stable) and tested with using the example code with `flutter run --no-sound-null-safety`, slightly modified to give non-null values to `QRExample`, though.
